### ISSUE TITLE
Can't compile the project

### ISSUE THREAD

**Issue by ScrappyCocco** [TheBenPerson/SBTool#1]
Could you please provide a compiled .exe?
I'm getting errors at building it by myself on Windows

**Comment by ben-stockett** [comment]
Sorry to hear that and sorry for the late reply. The issue (should) be fixed now.
In any case, here is the exe: [sbtool.exe.zip](https://github.com/TheBenPerson/SBTool/files/2710830/sbtool.exe.zip)

**Comment by ScrappyCocco** [comment]
Thank you, now i compiled it successfully. I'm gonna try soon if i'm able to use it and it works.
You should upload a compiled release in the [releases](https://github.com/TheBenPerson/SBTool/releases) pages anyway.
Thank you
